### ISSUE TITLE
NoSuchPathError when running the `bug_localization/src/baselines/run_baseline.py`

### ISSUE THREAD

**Issue by hminooei** [JetBrains-Research/lca-baselines#10]
When I run the `bug_localization/src/baselines/run_baseline.py` after it downloads the repos, it seems to be successfully running through them until it reaches the following:

```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/minooei/.pyenv/versions/3.11.7/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/minooei/.pyenv/versions/3.11.7/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/minooei/.cursor/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/minooei/.cursor/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/minooei/.cursor/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/minooei/.cursor/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/minooei/.cursor/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/minooei/.cursor/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/minooei/code/lca-baselines/bug_localization/src/baselines/run_baseline.py", line 47, in <module>
    main()
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/minooei/code/lca-baselines/bug_localization/src/baselines/run_baseline.py", line 28, in main
    for dp, repo_content, changed_files in data_src:
  File "/Users/minooei/code/lca-baselines/bug_localization/src/baselines/data_sources/hf_data_source.py", line 77, in __iter__
    repo_content = get_repo_content_on_commit(repo_path, dp['base_sha'],
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/minooei/code/lca-baselines/bug_localization/src/utils/git_utils.py", line 140, in get_repo_content_on_commit
    repo = git.Repo(repo_path)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/minooei/code/lca-baselines/env/lib/python3.11/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /Users/minooei/code/lca-baselines/bug_localization/repos/plotly__plotly.py
```

which seems to complain about the `plotly__plotly.py` not existing, and that's right, I only see `plotly__plotly` in the repos folder.

**Comment by tiginamaria** [comment]
Hi! Apologies for the delayed response—our team had a busy month with vacations and side projects. 

We've reproduced and fixed the issue you reported. The problem was that the [Plotly repo](https://github.com/plotly/plotly.py) includes .py in its name (plotly.py), and our loading process was ignoring this .py suffix.
The issue has now been resolved. Please pull the latest changes from the main branch in our repo, which includes the [fix](https://github.com/JetBrains-Research/lca-baselines/commit/977d200d2c2c5dc825190c5293db8e25057ff698). 

Thank you for your patience!
